#config_version=5
# sequence_shots:
#   left_ramp:
#     switch_sequence: s_left_ramp_enter, s_left_ramp_exit
#     sequence_timeout: 3s
#   right_ramp:
#     switch_sequence: s_right_ramp_enter, s_right_ramp_exit
#     sequence_timeout: 3s
#   right_orbit:
#     switch_sequence: s_right_freeway, s_left_loop, s_upper_left_flipper_gate,
#     sequence_timeout: 3s
